services:
  postgres:
    image: postgres
    build:
      context: ./postgres
    ports:
      - "5432:5432"
  wildfly:
    image: wildfly
    build:
      context: ./wildfly
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    depends_on:
      - postgres